export const ADD_PRODUCT_DATA = 'ADD_PRODUCT_DATA';
export const UPDATE_PRODUCT_TITLE = 'UPDATE_PRODUCT_TITLE';
export const UPDATE_PRODUCT_BODY = 'UPDATE_PRODUCT_BODY';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_COMPONENT_DATA = 'ADD_COMPONENT_DATA';
export const UPDATE_COMPONENT_TITLE = 'UPDATE_COMPONENT_TITLE';
export const UPDATE_COMPONENT_BODY = 'UPDATE_COMPONENT_BODY';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const ADD_WORKSHOP_DATA = 'ADD_WORKSHOP_DATA';
export const UPDATE_WORKSHOP_TITLE = 'UPDATE_WORKSHOP_TITLE';
export const UPDATE_WORKSHOP_BODY = 'UPDATE_WORKSHOP_BODY';
export const DELETE_WORKSHOP = 'DELETE_WORKSHOP';

export const ADD_ROUTE_DATA = 'ADD_ROUTE_DATA';
export const UPDATE_ROUTE_TITLE = 'UPDATE_ROUTE_TITLE';
export const UPDATE_ROUTE_BODY = 'UPDATE_ROUTE_BODY';
export const DELETE_ROUTE = 'DELETE_ROUTE';

export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_START = 'FETCH_PROJECT_START';
export const FETCH_END = 'FETCH_PROJECT_END';
export const FETCH_PROJECT_ERROR = 'FETCH_PROJECT_ERROR';
export const SET_CHOSEN_ITEM = 'SET_CHOSEN_ITEM';
export const TOGGLE_PACK = 'TOGGLE_PACK';
export const CLEAR_CHOSEN_ITEM = 'CLEAR_CHOSEN_ITEM';
export const SET_BODY_CHANGING = 'SET_BODY_CHANGING';
